pr:
  branches:
    include:
    - '*' 

variables:
- group: 'orch-key-vault-dev'
- name: 'powershellModuleName'
  value: 'DsbRobotOrchestration'
- name: 'runTestsWithCoverage'
  value: '$false'

stages:
- stage: RunTests
  displayName: Run Tests
  jobs:
  - job: PesterTests
    displayName: Run Pester tests for powershell scripts 
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@0
      displayName: Use NuGet 4.x
      inputs:
        versionSpec: 4.x
        checkLatest: true
    - powershell: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck

        # Install the package "functional" to do comparisons on hashtables in 
        # tests. Package can be found: https://www.powershellgallery.com/packages/functional 
        Install-Module -Name functional -Force -Scope CurrentUser -SkipPublisherCheck
      displayName: Install Nuget and update Pester
    - powershell: |
        $withCoverage = $(runTestsWithCoverage) -eq $true
        $results = $null;
        if ($withCoverage) {
          $results = Invoke-Pester -PassThru -CodeCoverage ./$(powershellModuleName)/$(powershellModuleName).psm1
        } 
        else {
          $results = Invoke-Pester -PassThru
        }
        if ($results.failedCount -ne 0) { 
            Throw "There were failing tests"
        }
      displayName: Run pester tests with or without code coverage
      workingDirectory: $(Build.Repository.LocalPath)
      env:
        HUMIO_INGEST_TOKEN: $(humio-ingest-token)