
name: 'powershell module push'

trigger:
  branches:
    include:
    - releases/*

pr:
  branches:
    exclude:
    - '*'
     
variables:
  - group: 'orch-key-vault-dev'
  - name: 'powershellModuleName'
    value: 'DsbRobotOrchestration'

jobs:
- job: PublishModule
  displayName: Publish module to Powershell gallery
  pool:
    vmName: windows-latest
  steps:
  - powershell: |
      Publish-Module -Path $(Build.Repository.LocalPath)\$(powershellModuleName) -NugetApiKey "$env:GALLERY_TOKEN" -Force
    displayName: 'PowerShell Gallery Packager '
    env:
      GALLERY_TOKEN: $(powershell-gallery-token)